### PR TITLE
Add CLI

### PR DESCRIPTION
**Pull request by zeke**
I saw that the old ghub had a CLI and assumed it was a tool for doing lookups, but it appears to actually have just been [a way to start the server](https://github.com/juliangruber/ghub.io/blob/f5dffef663588cb0e58e9897553a1f786f808762/bin/ghub.io.js). Is that right, @juliangruber?

Please let me know what you think of this new CLI behavior.

### CODE REVIEW

**Comment by juliangruber** [comment]
Correct, the CLI was just used for starting the server. The new CLI looks great to me :)

**Comment by Kikobeats** [comment]
Just for inspiration, time ago I created similar CLI but for npm:
https://github.com/Kikobeats/npm-url

**Comment by zeke** [comment]
Had a thought while falling asleep: Would be cool if the CLI also accepted a newline-delimited list on STDIN, e.g. `node cli.js | egrep '^level' | head -n 10 | ghub`

**Comment by zeke** [comment]
Any bright ideas on how to write tests for this? I usually use [nixt](https://github.com/vesln/nixt) to test CLIs which makes it easy to check stdout and exit codes, but I'm not sure how to use it to check that `open` is called... 🤔

**Comment by juliangruber** [comment]
Maybe put an `open` cli into the npm path which prints the path to be opened to `stdout`?

**Comment by zeke** [comment]
> Maybe put an open cli

Yeah, but this is using the `open` module programmatically, not a binary.

Just gonna ship this as-is with no test coverage on the CLI. We can always revisit if it proves buggy.

**Comment by zeke** [comment]
```
$ np major   
 ✔ Prerequisite check
 ✔ Git
 ✔ Cleanup
 ✔ Installing dependencies using npm
 ✔ Running tests
 ✔ Bumping version using npm
 ✔ Publishing package
 ✔ Pushing tags

 ghub.io 2.0.0 published 🎉
```

**Comment by zeke** [comment]
Oops. Published as `ghub.io` instead of `ghub`. Luckily npm allows unpublishes for 24 hours.

Fixed: https://www.npmjs.com/package/ghub

**Comment by juliangruber** [comment]
> Yeah, but this is using the open module programmatically, not a binary.

The open module itself uses the open binary, see: https://github.com/pwnall/node-open/blob/master/lib/open.js#L31. So it should be patchable.

**Pull request merged**
